from __future__ import annotations

import ast
import json
import os
import re
import time
from typing import Any, Dict, List, Literal, Optional, Set, Tuple
from pydantic import BaseModel, ConfigDict, Field

import httpx

from app.tools import execute_tool_call


# ---------------------------------------------------------------------------
# Structured Output Models (Pydantic)
# ---------------------------------------------------------------------------

class DependencyNode(BaseModel):
    model_config = ConfigDict(extra="ignore")
    name: str
    version: Optional[str] = None
    dependency_type: str = "runtime"  # runtime, dev, peer, system


class ArchitectBlueprint(BaseModel):
    """Structured architectural blueprint generated by ArchitectAgent."""
    model_config = ConfigDict(extra="ignore")

    goal: str = ""
    framework: str = "Generic / Dockerized"
    runtime_paradigm: str = "Containerized Service"
    runtime_version: Optional[str] = None
    entrypoint: Optional[str] = None
    port: Optional[int] = None
    dependency_graph: Dict[str, List[str]] = Field(default_factory=dict)
    execution_steps: List[str] = Field(default_factory=list)
    files_to_modify: List[str] = Field(default_factory=list)
    files_to_create: List[str] = Field(default_factory=list)
    risk_assessment: List[str] = Field(default_factory=list)
    rationale: str = ""
    timestamp: float = Field(default_factory=time.time)


class CodePatch(BaseModel):
    """Surgical patch or file creation produced and verified by CoderAgent."""
    model_config = ConfigDict(extra="ignore")

    file_path: str
    action: Literal["edit", "write", "verify"] = "edit"
    target: Optional[str] = None
    replacement: Optional[str] = None
    content: Optional[str] = None
    syntax_valid: bool = True
    ast_safe: bool = True
    error_message: Optional[str] = None
    details: str = ""
    timestamp: float = Field(default_factory=time.time)


class VerificationReport(BaseModel):
    """Validation report generated by VerifierAgent."""
    model_config = ConfigDict(extra="ignore")

    status: Literal["passed", "failed", "warning"] = "warning"
    build_integrity: bool = False
    container_readiness: bool = False
    network_endpoints_live: bool = False
    errors_found: List[str] = Field(default_factory=list)
    tested_endpoints: List[Dict[str, Any]] = Field(default_factory=list)
    log_anomalies: List[str] = Field(default_factory=list)
    summary: str = ""
    timestamp: float = Field(default_factory=time.time)


class PermissionRequest(BaseModel):
    """High-risk tool permission request to engage user approval."""
    model_config = ConfigDict(extra="ignore")

    tool_name: str
    arguments: Dict[str, Any] = Field(default_factory=dict)
    risk_level: Literal["high", "medium", "low"] = "high"
    description: str = ""
    command: Optional[str] = None
    token: Optional[str] = None


class SwarmContext(BaseModel):
    """Shared state and context managed by SupervisorAgent across subagents."""
    model_config = ConfigDict(extra="ignore")

    goal: str = ""
    project_id: Optional[str] = None
    deployment_id: Optional[str] = None
    user_id: Optional[str] = None
    blueprint: Optional[ArchitectBlueprint] = None
    patches: List[CodePatch] = Field(default_factory=list)
    verification: Optional[VerificationReport] = None
    pending_permissions: List[PermissionRequest] = Field(default_factory=list)
    lifecycle_events: List[str] = Field(default_factory=list)
    shared_data: Dict[str, Any] = Field(default_factory=dict)
    created_at: float = Field(default_factory=time.time)


# ---------------------------------------------------------------------------
# 1. ArchitectAgent
# ---------------------------------------------------------------------------

class ArchitectAgent:
    """
    ArchitectAgent:
    - Generates structured architectural blueprints
    - Analyzes project dependency graphs
    - Detects framework/runtime paradigms
    - Produces step-by-step execution plans
    """

    ROLE: str = "Architect Subagent"
    ICON: str = "🏛️"

    def __init__(self, name: str = "ArchitectAgent"):
        self.name = name

    def detect_paradigm(
        self,
        files: List[str],
        package_json_str: Optional[str] = None,
        dockerfile_str: Optional[str] = None,
        requirements_str: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Detect framework, runtime, and architecture paradigm from workspace layout and configs."""
        files_lower = {f.lower().replace("\\", "/") for f in files}
        
        framework = "Standard Application"
        runtime = "Unknown Runtime"
        paradigm = "Single Service Container"
        entrypoint = None
        port = None

        # Node / JS / TS ecosystem
        if "package.json" in [os.path.basename(f) for f in files_lower] or package_json_str:
            runtime = "Node.js"
            deps: Dict[str, str] = {}
            scripts: Dict[str, str] = {}
            if package_json_str:
                try:
                    pkg = json.loads(package_json_str)
                    deps.update(pkg.get("dependencies", {}))
                    deps.update(pkg.get("devDependencies", {}))
                    scripts.update(pkg.get("scripts", {}))
                except Exception:
                    pass

            if "next" in deps:
                framework = "Next.js (React)"
                paradigm = "Server-Side Rendered (SSR) Web App"
                port = 3000
                entrypoint = "npm run start" if "start" in scripts else "npm run dev"
            elif "nuxt" in deps:
                framework = "Nuxt.js (Vue)"
                paradigm = "Fullstack Vue SSR"
                port = 3000
            elif "@nestjs/core" in deps:
                framework = "NestJS"
                paradigm = "Modular Enterprise REST / GraphQL API"
                port = 3000
            elif "express" in deps:
                framework = "Express.js"
                paradigm = "RESTful HTTP Microservice"
                port = 3000 or 8080
            elif "fastify" in deps:
                framework = "Fastify"
                paradigm = "High-Throughput Node HTTP Service"
                port = 3000
            elif "react-scripts" in deps or "vite" in deps:
                framework = "Vite / React SPA"
                paradigm = "Static Single Page App with Dev Proxy"
                port = 5173 if "vite" in deps else 3000

        # Python ecosystem
        elif any(f in files_lower for f in ["requirements.txt", "pyproject.toml", "pipfile", "setup.py"]) or requirements_str:
            runtime = "Python"
            req_text = requirements_str or ""
            if "fastapi" in req_text.lower():
                framework = "FastAPI (ASGI)"
                paradigm = "Asynchronous High-Performance API"
                port = 8000
                entrypoint = "uvicorn main:app --host 0.0.0.0 --port 8000"
            elif "django" in req_text.lower():
                framework = "Django"
                paradigm = "Monolithic MVC Web Application"
                port = 8000
            elif "flask" in req_text.lower():
                framework = "Flask"
                paradigm = "Lightweight WSGI Microservice"
                port = 5000
            else:
                framework = "Python CLI / Worker"
                paradigm = "Background Processing Worker"

        # Go ecosystem
        elif any(f.endswith("go.mod") for f in files_lower):
            runtime = "Go"
            framework = "Go Module"
            paradigm = "Compiled Microservice"
            port = 8080

        # Rust ecosystem
        elif any(f.endswith("cargo.toml") for f in files_lower):
            runtime = "Rust"
            framework = "Cargo Project"
            paradigm = "High-Performance Systems Microservice"
            port = 8080

        # Docker analysis
        if dockerfile_str:
            paradigm = f"Containerized ({paradigm})"
            # Find EXPOSE
            expose_match = re.search(r"^\s*EXPOSE\s+(\d+)", dockerfile_str, re.MULTILINE | re.IGNORECASE)
            if expose_match:
                port = int(expose_match.group(1))

        return {
            "framework": framework,
            "runtime": runtime,
            "paradigm": paradigm,
            "port": port,
            "entrypoint": entrypoint,
        }

    def analyze_dependency_graph(
        self,
        package_json_str: Optional[str] = None,
        requirements_str: Optional[str] = None,
        docker_compose_str: Optional[str] = None,
    ) -> Dict[str, List[str]]:
        """Construct a lightweight dependency graph showing interconnected dependencies and tiers."""
        graph: Dict[str, List[str]] = {}

        if package_json_str:
            try:
                pkg = json.loads(package_json_str)
                prod_deps = list(pkg.get("dependencies", {}).keys())
                dev_deps = list(pkg.get("devDependencies", {}).keys())
                graph["runtime_dependencies"] = prod_deps[:25]
                if dev_deps:
                    graph["development_dependencies"] = dev_deps[:15]
            except Exception:
                pass

        if requirements_str:
            reqs: List[str] = []
            for line in requirements_str.splitlines():
                line = line.strip()
                if line and not line.startswith("#") and not line.startswith("-"):
                    name = re.split(r"[=<>!~]", line)[0].strip()
                    if name:
                        reqs.append(name)
            if reqs:
                graph["python_packages"] = reqs[:25]

        if docker_compose_str:
            services: List[str] = []
            for line in docker_compose_str.splitlines():
                m = re.match(r"^\s{2}([a-zA-Z0-9_-]+):", line)
                if m and m.group(1) not in {"version", "services", "networks", "volumes"}:
                    services.append(m.group(1))
            if services:
                graph["compose_services"] = services

        return graph

    def create_blueprint(
        self,
        goal: str,
        files: Optional[List[str]] = None,
        package_json_str: Optional[str] = None,
        dockerfile_str: Optional[str] = None,
        requirements_str: Optional[str] = None,
        logs: Optional[str] = None,
    ) -> ArchitectBlueprint:
        """Synthesize a complete, structured Architectural Blueprint."""
        file_list = files or []
        paradigm_info = self.detect_paradigm(
            file_list,
            package_json_str=package_json_str,
            dockerfile_str=dockerfile_str,
            requirements_str=requirements_str,
        )
        dep_graph = self.analyze_dependency_graph(
            package_json_str=package_json_str,
            requirements_str=requirements_str,
        )

        steps: List[str] = [
            f"1. Workspace Inspection: Verify files in {paradigm_info['framework']} codebase.",
            "2. Dependency Graph Resolution: Validate integrity of runtime packages and build configurations.",
            "3. Surgical Code Modifications: Apply AST-safe patches to resolve configuration or syntax flaws.",
            "4. Workspace Rebuild: Queue container rebuild reflecting modified files.",
            "5. Runtime & Network Verification: Poll deployment readiness and probe health endpoints.",
        ]

        risks: List[str] = []
        if not dockerfile_str and "dockerfile" not in [os.path.basename(f).lower() for f in file_list]:
            risks.append("No explicit Dockerfile found; relies on automated builder detection.")
        if paradigm_info.get("port") is None:
            risks.append("Container listening port not explicitly declared in source configuration.")
        if logs and any(err in logs.lower() for err in ["syntaxerror", "cannot find module", "crashloop"]):
            risks.append("Pre-existing runtime crash detected in deployment logs.")

        files_to_modify: List[str] = []
        if package_json_str and "package.json" in [os.path.basename(f) for f in file_list]:
            files_to_modify.append("package.json")
        elif requirements_str and "requirements.txt" in [os.path.basename(f) for f in file_list]:
            files_to_modify.append("requirements.txt")

        return ArchitectBlueprint(
            goal=goal,
            framework=paradigm_info["framework"],
            runtime_paradigm=paradigm_info["paradigm"],
            entrypoint=paradigm_info.get("entrypoint"),
            port=paradigm_info.get("port"),
            dependency_graph=dep_graph,
            execution_steps=steps,
            files_to_modify=files_to_modify,
            files_to_create=[],
            risk_assessment=risks,
            rationale=f"Architected plan for {paradigm_info['framework']} under {paradigm_info['paradigm']} paradigm.",
        )

    def format_blueprint_markdown(self, blueprint: ArchitectBlueprint) -> str:
        """Render markdown representation of blueprint."""
        lines = [
            f"### {self.ICON} Architectural Blueprint",
            f"- **Framework**: `{blueprint.framework}`",
            f"- **Runtime Paradigm**: `{blueprint.runtime_paradigm}`",
        ]
        if blueprint.port:
            lines.append(f"- **Target Port**: `{blueprint.port}`")
        if blueprint.entrypoint:
            lines.append(f"- **Entrypoint**: `{blueprint.entrypoint}`")
        
        lines.append("\n**Execution Plan**:")
        for step in blueprint.execution_steps:
            lines.append(f"- {step}")
            
        if blueprint.risk_assessment:
            lines.append("\n**Risk Assessment**:")
            for risk in blueprint.risk_assessment:
                lines.append(f"- ⚠️ {risk}")

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# 2. CoderAgent
# ---------------------------------------------------------------------------

class CoderAgent:
    """
    CoderAgent:
    - Performs surgical, AST-safe file edits
    - Verifies syntax integrity across Python, JSON, JS/TS
    - Creates new files with complete implementations
    """

    ROLE: str = "Coder Subagent"
    ICON: str = "⚡"

    def __init__(self, name: str = "CoderAgent"):
        self.name = name

    def verify_syntax(self, file_path: str, code: str) -> Tuple[bool, Optional[str]]:
        """Verify syntax integrity of proposed code content."""
        ext = os.path.splitext(file_path)[1].lower()

        # Python AST verification
        if ext == ".py":
            try:
                ast.parse(code, filename=file_path)
                return True, None
            except SyntaxError as exc:
                return False, f"Python SyntaxError at line {exc.lineno}: {exc.msg}"
            except Exception as exc:
                return False, f"Python AST parse error: {str(exc)}"

        # JSON verification
        if ext in {".json", ".jsonc"}:
            try:
                json.loads(code)
                return True, None
            except json.JSONDecodeError as exc:
                return False, f"JSON syntax error at line {exc.lineno}, col {exc.colno}: {exc.msg}"

        # JavaScript / TypeScript balanced delimiter verification
        if ext in {".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs"}:
            balanced, msg = self._check_delimiters(code)
            if not balanced:
                return False, f"JS/TS delimiter mismatch: {msg}"
            return True, None

        # General file - basic sanity check
        return True, None

    def _check_delimiters(self, text: str) -> Tuple[bool, Optional[str]]:
        """Check matching braces, brackets, parentheses, and quotes in JS/TS text."""
        stack: List[Tuple[str, int]] = []
        matching = {')': '(', '}': '{', ']': '['}
        line_num = 1

        in_line_comment = False
        in_block_comment = False
        in_string: Optional[str] = None
        escape = False

        i = 0
        n = len(text)
        while i < n:
            ch = text[i]
            if ch == '\n':
                line_num += 1
                in_line_comment = False

            if in_line_comment:
                i += 1
                continue

            if in_block_comment:
                if ch == '*' and i + 1 < n and text[i + 1] == '/':
                    in_block_comment = False
                    i += 2
                    continue
                i += 1
                continue

            if escape:
                escape = False
                i += 1
                continue

            if ch == '\\':
                escape = True
                i += 1
                continue

            if in_string:
                if ch == in_string:
                    in_string = None
                i += 1
                continue

            # Comment starts
            if ch == '/' and i + 1 < n:
                if text[i + 1] == '/':
                    in_line_comment = True
                    i += 2
                    continue
                elif text[i + 1] == '*':
                    in_block_comment = True
                    i += 2
                    continue

            # String starts
            if ch in {'"', "'", '`'}:
                in_string = ch
                i += 1
                continue

            if ch in matching.values():
                stack.append((ch, line_num))
            elif ch in matching:
                expected = matching[ch]
                if not stack:
                    return False, f"Unmatched '{ch}' at line {line_num}"
                last_open, open_line = stack.pop()
                if last_open != expected:
                    return False, f"Mismatched closing '{ch}' at line {line_num} (opened '{last_open}' at line {open_line})"

            i += 1

        if stack:
            unclosed, open_line = stack[-1]
            return False, f"Unclosed '{unclosed}' from line {open_line}"

        return True, None

    def is_ast_safe_edit(
        self,
        original_content: str,
        target: str,
        replacement: str,
        file_path: str = "",
    ) -> Tuple[bool, str]:
        """Validate if a find-and-replace edit preserves AST and syntax validity."""
        if target not in original_content:
            return False, f"Target string not found in {file_path or 'file'}."

        occurrences = original_content.count(target)
        if occurrences > 1:
            return False, f"Target string is ambiguous ({occurrences} occurrences found). Provide unique context."

        # Perform trial edit
        modified_content = original_content.replace(target, replacement, 1)

        # Verify syntax on candidate result
        is_valid, err = self.verify_syntax(file_path, modified_content)
        if not is_valid:
            return False, f"Edit introduces syntax invalidity: {err}"

        return True, "Edit is AST-safe and syntactically valid."

    def prepare_patch(
        self,
        file_path: str,
        action: Literal["edit", "write"],
        target: Optional[str] = None,
        replacement: Optional[str] = None,
        content: Optional[str] = None,
        original_content: Optional[str] = None,
    ) -> CodePatch:
        """Create a validated CodePatch object."""
        if action == "edit":
            if not target or replacement is None:
                return CodePatch(
                    file_path=file_path,
                    action="edit",
                    syntax_valid=False,
                    ast_safe=False,
                    error_message="Target and replacement are required for surgical edit.",
                )
            if original_content is not None:
                is_safe, msg = self.is_ast_safe_edit(original_content, target, replacement, file_path)
                return CodePatch(
                    file_path=file_path,
                    action="edit",
                    target=target,
                    replacement=replacement,
                    syntax_valid=is_safe,
                    ast_safe=is_safe,
                    details=msg,
                    error_message=None if is_safe else msg,
                )
            return CodePatch(
                file_path=file_path,
                action="edit",
                target=target,
                replacement=replacement,
                syntax_valid=True,
                ast_safe=True,
                details="Prepared surgical edit.",
            )

        elif action == "write":
            if content is None:
                return CodePatch(
                    file_path=file_path,
                    action="write",
                    syntax_valid=False,
                    ast_safe=False,
                    error_message="Content is required for write patch.",
                )
            is_valid, err = self.verify_syntax(file_path, content)
            return CodePatch(
                file_path=file_path,
                action="write",
                content=content,
                syntax_valid=is_valid,
                ast_safe=is_valid,
                details="Complete file implementation ready.",
                error_message=err,
            )

        return CodePatch(file_path=file_path, action="verify", details="No-op verify patch.")

    async def execute_patch(
        self,
        patch: CodePatch,
        user_id: str,
        project_id: Optional[str] = None,
        deployment_id: Optional[str] = None,
    ) -> Dict[str, Any]:
        """Execute the validated patch against the backend workspace tool."""
        if not patch.syntax_valid or not patch.ast_safe:
            return {
                "status": "error",
                "error": f"Refusing to apply invalid patch: {patch.error_message or 'AST syntax violation'}",
            }

        args: Dict[str, Any] = {"file_path": patch.file_path}
        if project_id:
            args["project_id"] = project_id
        if deployment_id:
            args["deployment_id"] = deployment_id

        if patch.action == "edit" and patch.target and patch.replacement is not None:
            args["target"] = patch.target
            args["replacement"] = patch.replacement
            return await execute_tool_call("workspace_edit_file", args, user_id)
        elif patch.action == "write" and patch.content is not None:
            args["content"] = patch.content
            return await execute_tool_call("workspace_write_file", args, user_id)

        return {"status": "error", "error": f"Unsupported patch action: {patch.action}"}


# ---------------------------------------------------------------------------
# 3. VerifierAgent
# ---------------------------------------------------------------------------

class VerifierAgent:
    """
    VerifierAgent:
    - Validates workspace build integrity
    - Verifies container readiness
    - Checks logs for fatal errors and crash patterns
    - Probes live network endpoints
    """

    ROLE: str = "Verifier Subagent"
    ICON: str = "🔍"

    ERROR_SIGNATURES = [
        re.compile(r"SyntaxError:\s*.+", re.IGNORECASE),
        re.compile(r"Cannot find module\s*['\"].+?['\"]", re.IGNORECASE),
        re.compile(r"ModuleNotFoundError:\s*No module named\s*['\"].+?['\"]", re.IGNORECASE),
        re.compile(r"Traceback \(most recent call last\):", re.IGNORECASE),
        re.compile(r"npm ERR!\s*.+", re.IGNORECASE),
        re.compile(r"yarn error\s*.+", re.IGNORECASE),
        re.compile(r"EADDRINUSE|address already in use", re.IGNORECASE),
        re.compile(r"ECONNREFUSED|connection refused", re.IGNORECASE),
        re.compile(r"CrashLoopBackOff", re.IGNORECASE),
        re.compile(r"OutOfMemoryError|OOMKilled", re.IGNORECASE),
        re.compile(r"Segmentation fault", re.IGNORECASE),
        re.compile(r"panic:\s*.+", re.IGNORECASE),
        re.compile(r"FATAL:\s*.+", re.IGNORECASE),
    ]

    def __init__(self, name: str = "VerifierAgent"):
        self.name = name

    def check_logs(self, logs: str) -> List[str]:
        """Scan logs for critical error patterns and crash signatures."""
        found_errors: List[str] = []
        if not logs:
            return found_errors

        for sig in self.ERROR_SIGNATURES:
            for match in sig.finditer(logs):
                msg = match.group(0).strip()
                if msg and msg not in found_errors:
                    found_errors.append(msg)
                    if len(found_errors) >= 10:
                        break
            if len(found_errors) >= 10:
                break

        return found_errors

    async def probe_endpoint(self, url: str, timeout: float = 6.0) -> Dict[str, Any]:
        """Probe live network endpoint for responsiveness and health status."""
        result: Dict[str, Any] = {
            "url": url,
            "status_code": None,
            "healthy": False,
            "latency_ms": 0,
            "error": None,
        }
        start = time.perf_counter()
        try:
            async with httpx.AsyncClient(timeout=timeout, follow_redirects=True) as client:
                resp = await client.get(url)
                result["latency_ms"] = int((time.perf_counter() - start) * 1000)
                result["status_code"] = resp.status_code
                result["healthy"] = 200 <= resp.status_code < 400
        except Exception as exc:
            result["latency_ms"] = int((time.perf_counter() - start) * 1000)
            result["error"] = str(exc)
            result["healthy"] = False

        return result

    def validate_build_integrity(
        self,
        deployment_status: Dict[str, Any],
        logs: str = "",
        tested_endpoints: Optional[List[Dict[str, Any]]] = None,
    ) -> VerificationReport:
        """Synthesize overall build and runtime verification report."""
        status_val = str(deployment_status.get("status", "")).lower()
        build_ok = status_val in {"running", "ready", "active", "built", "succeeded", "success"}
        container_ready = status_val in {"running", "ready", "active"}

        errors = self.check_logs(logs)
        endpoints = tested_endpoints or []
        endpoints_live = bool(endpoints) and all(ep.get("healthy", False) for ep in endpoints)

        overall_status: Literal["passed", "failed", "warning"] = "passed"
        if status_val in {"failed", "error", "crashloop"} or errors or (endpoints and not endpoints_live):
            overall_status = "failed"
        elif not build_ok or not container_ready or not endpoints or deployment_status.get('verified') is not True:
            overall_status = "warning"

        summary_parts = []
        if container_ready:
            summary_parts.append("Container is active and in running state.")
        else:
            summary_parts.append(f"Container status is '{status_val}'.")

        if errors:
            summary_parts.append(f"{len(errors)} error signature(s) detected in logs.")
        else:
            summary_parts.append("No crash signatures detected in logs.")

        if endpoints:
            live_count = sum(1 for e in endpoints if e.get("healthy"))
            summary_parts.append(f"{live_count}/{len(endpoints)} endpoints responsive.")

        return VerificationReport(
            status=overall_status,
            build_integrity=build_ok,
            container_readiness=container_ready,
            network_endpoints_live=endpoints_live,
            errors_found=errors,
            tested_endpoints=endpoints,
            summary=" ".join(summary_parts),
        )

    def format_verification_markdown(self, report: VerificationReport) -> str:
        """Format verification report into clean markdown."""
        icon = "✅" if report.status == "passed" else ("⚠️" if report.status == "warning" else "❌")
        lines = [
            f"### {self.ICON} Verification Report ({icon} {report.status.upper()})",
            f"- **Build Integrity**: {'Pass' if report.build_integrity else 'Fail'}",
            f"- **Container Readiness**: {'Ready' if report.container_readiness else 'Not Ready'}",
            f"- **Network Endpoints**: {'Live' if report.network_endpoints_live else 'Unreachable'}",
            f"- **Summary**: {report.summary}",
        ]
        if report.errors_found:
            lines.append("\n**Detected Log Anomalies**:")
            for err in report.errors_found[:5]:
                lines.append(f"- `{err}`")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# 4. SupervisorAgent
# ---------------------------------------------------------------------------

class SupervisorAgent:
    """
    SupervisorAgent:
    - Orchestrates the subagent lifecycle
    - Manages shared SwarmContext state
    - Enforces human-in-the-loop tool permissions
    - Synthesizes the unified final multi-agent report
    """

    ROLE: str = "Supervisor"
    ICON: str = "👑"

    HIGH_RISK_TOOLS: Set[str] = {
        "terminal_run_command",
        "workspace_trigger_rebuild",
        "deploy_project",
        "workspace_write_file",
        "workspace_edit_file",
        "scale_deployment",
        "repair_deployment",
        "trigger_build",
    }

    def __init__(
        self,
        goal: str = "",
        project_id: Optional[str] = None,
        deployment_id: Optional[str] = None,
        user_id: Optional[str] = None,
    ):
        self.context = SwarmContext(
            goal=goal,
            project_id=project_id,
            deployment_id=deployment_id,
            user_id=user_id,
        )
        self.architect = ArchitectAgent()
        self.coder = CoderAgent()
        self.verifier = VerifierAgent()

    def record_lifecycle_event(self, event: str) -> None:
        """Append subagent lifecycle transition to context."""
        self.context.lifecycle_events.append(f"[{time.strftime('%H:%M:%S')}] {event}")

    def requires_permission(
        self,
        tool_name: str,
        tool_args: Dict[str, Any],
        runtime_permissions: Dict[str, Any],
        agent_access_mode: Optional[str] = None,
    ) -> bool:
        """
        Determine whether executing tool_name requires human-in-the-loop authorization.
        Enforces policy:
        - If agent_access_mode == 'ask' and tool is high-risk mutating tool
        - If tool_name == 'terminal_run_command' and remote_terminal == 'ask'
        - If require_confirmation flag is explicitly set
        """
        mode = agent_access_mode or runtime_permissions.get("agent_access_mode") or "ask"
        remote_term = runtime_permissions.get("remote_terminal", "ask")
        require_confirm = runtime_permissions.get("require_confirmation", mode != "full_access")

        # Remote terminal specific check
        if tool_name == "terminal_run_command" and remote_term == "ask":
            return True

        # Mutating tool check
        if tool_name in self.HIGH_RISK_TOOLS:
            if mode == "ask":
                return True
            if require_confirm and mode != "full_access":
                return True

        return False

    def is_confirmation_approved(
        self,
        tool_name: str,
        tool_args: Dict[str, Any],
        request_data: Any,
        history: Optional[List[Dict[str, str]]] = None,
    ) -> bool:
        """Consume an approval signed for this exact user, session and action.

        Narration, history and model-supplied boolean flags are never approval.
        The active main loop uses the same approval broker directly.
        """
        from .agent_runtime.approval import consume
        return consume(getattr(request_data, "approval_token", None), request_data, tool_name, tool_args)

    def create_permission_request(
        self,
        tool_name: str,
        tool_args: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Generate structured permission request payload for frontend interactive card."""
        cmd = tool_args.get("command") if tool_name == "terminal_run_command" else None
        desc = (
            f"Execute terminal command `{cmd}`"
            if cmd else
            f"Run high-risk tool `{tool_name}`"
        )
        return {
            "type": "permission_request",
            "tool_name": tool_name,
            "arguments": tool_args,
            "risk_level": "high",
            "description": desc,
            "command": cmd,
        }

    def synthesize_report(self, custom_summary: Optional[str] = None) -> str:
        """Synthesize unified final multi-agent report."""
        sections = ["## 🚀 Strategic AI Architect Report\n"]

        if self.context.blueprint:
            sections.append(self.architect.format_blueprint_markdown(self.context.blueprint))
            sections.append("\n---\n")

        if self.context.patches:
            sections.append(f"### {self.coder.ICON} Applied Workspace Patches")
            for patch in self.context.patches:
                status_badge = "✅ AST-Safe" if patch.ast_safe else "⚠️ Warning"
                sections.append(f"- **{patch.file_path}** ({patch.action.upper()}) — {status_badge}: {patch.details}")
            sections.append("\n---\n")

        if self.context.verification:
            sections.append(self.verifier.format_verification_markdown(self.context.verification))
            sections.append("\n---\n")

        if custom_summary:
            sections.append(f"### 📋 Summary & Recommendations\n{custom_summary}")

        return "\n".join(sections)
