"""Deterministic Linux recipes from manifest evidence; no application substitutes."""
import json
from pathlib import Path

PYTHON_SETUP = 'RUN command -v python3 || (command -v apt-get && apt-get update && apt-get install -y --no-install-recommends python3 ca-certificates && rm -rf /var/lib/apt/lists/*) || (command -v apk && apk add --no-cache python3 ca-certificates)\n'


def choose(root, discovery, config):
    root = Path(root)
    toolchains = discovery.get('toolchains', [])
    primary = [t for t in toolchains if t['kind'] in {'node', 'python', 'go', 'rust', 'java', 'dotnet', 'ruby', 'php'}]
    # Root manifests are stronger evidence than helper scripts/version files.
    manifests = {'node': ('package.json',), 'python': ('pyproject.toml', 'requirements.txt', 'setup.py', 'setup.cfg'),
                 'go': ('go.mod',), 'rust': ('Cargo.toml',), 'java': ('pom.xml', 'build.gradle', 'build.gradle.kts'),
                 'ruby': ('Gemfile',), 'php': ('composer.json',)}
    present = [kind for kind, names in manifests.items() if any((root/name).is_file() for name in names)]
    if any(item['kind'] == 'dotnet' for item in primary): present.append('dotnet')
    if not present and any('/' not in item['path'] for item in discovery.get('python', [])): present = ['python']
    if len(present) != 1: return None
    selected = next((t for t in primary if t['kind'] == present[0]), None)
    if selected and selected['status'] != 'selected':
        raise ValueError('Automatic '+selected['kind']+' build needs compatible version evidence: '+'; '.join(selected['issues']))
    return selected


def dockerfile(root, discovery, config, contract):
    selected = choose(root, discovery, config)
    if not selected: return None
    kind, image = selected['kind'], selected['image']
    workload = contract['workload']
    if workload not in {'web', 'api', 'cli', 'job', 'worker', 'tcp', 'grpc'}: return None
    # Dependency detection cannot invent executable product behavior.
    if kind in {'ruby', 'php'} and not contract.get('entrypoint'): return None
    port = contract['port'] or 3000
    common = 'WORKDIR /app\nCOPY . .\n'
    launch = f'ENV PORT={port} HOME=/tmp\n'
    if workload != 'worker': launch += f'EXPOSE {port}\n'
    launcher = 'console_server.py' if kind == 'node' and workload in {'cli', 'job'} else 'launch.py'
    launch += 'USER 65534:65534\nCMD ["python3", "/app/.stackpilot-runtime/'+launcher+'"]\n'
    if kind in {'python', 'node', 'ruby', 'php'}:
        if kind == 'node' and not contract.get('entrypoint') and workload in {'web', 'api'}:
            package = json.loads((Path(root)/'package.json').read_text())
            scripts = package.get('scripts', {})
            if scripts.get('build') and not scripts.get('start'):
                text = '# Generated by StackPilot Linux recipes from version evidence\nFROM '+image+' AS builder\n'+PYTHON_SETUP+common
                text = text.replace('WORKDIR /app\n', 'ENV COREPACK_HOME=/opt/stackpilot-corepack NPM_CONFIG_CACHE=/tmp/.npm\nWORKDIR /app\n')
                text += 'RUN python3 .stackpilot-runtime/linux_build.py node-static\nFROM nginx:alpine\n'
                text += 'COPY --from=builder /stackpilot-output/ /usr/share/nginx/html/\nCOPY --from=builder /app/.stackpilot-tests.json /stackpilot-evidence/tests.json\n'
                nginx = f'server {{ listen {port}; server_name localhost; root /usr/share/nginx/html; index index.html; location / {{ try_files $uri $uri/ /index.html; }} }}'
                text += "RUN printf '%s' '"+nginx+"' > /etc/nginx/conf.d/default.conf\n"
                text += 'RUN mkdir -p /var/cache/nginx/client_temp /var/cache/nginx/proxy_temp /var/cache/nginx/fastcgi_temp /var/cache/nginx/uwsgi_temp /var/cache/nginx/scgi_temp && chmod -R 777 /var/cache/nginx /var/run /var/log/nginx\n'
                return text+f'USER 65534:65534\nEXPOSE {port}\nCMD ["nginx", "-g", "daemon off;"]\n'
        text = '# Generated by StackPilot Linux recipes from version evidence\nFROM '+image+'\n'
        if kind != 'python': text += PYTHON_SETUP
        if kind == 'php': text += 'COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer\n'
        if kind == 'node': text += 'ENV COREPACK_HOME=/opt/stackpilot-corepack NPM_CONFIG_CACHE=/tmp/.npm\n'
        text += common
        text += 'RUN python3 .stackpilot-runtime/linux_build.py '+kind+' && chown -R 65534:65534 /app\n'
        return text+launch
    if kind in {'go', 'rust'}:
        text = '# Generated by StackPilot Linux recipes from version evidence\nFROM '+image+' AS builder\n'+PYTHON_SETUP+common
        text += 'RUN python3 .stackpilot-runtime/compiled_build.py '+kind+' && python3 .stackpilot-runtime/repository_tests.py\n'
        text += 'FROM debian:bookworm-slim\n'+PYTHON_SETUP+'WORKDIR /app\n'
        if kind == 'rust': text += 'RUN apt-get update && apt-get install -y --no-install-recommends libstdc++6 && rm -rf /var/lib/apt/lists/*\n'
        text += 'COPY --from=builder /artifacts/server /app/server\nCOPY --from=builder /artifacts/.stackpilot-entry.json /app/.stackpilot-entry.json\n'
        text += 'COPY --from=builder /app/.stackpilot-tests.json /stackpilot-evidence/tests.json\n'
        text += 'COPY .stackpilot-runtime /app/.stackpilot-runtime\nCOPY .stackpilot-plan.json /app/.stackpilot-plan.json\n'
        text += 'RUN chown -R 65534:65534 /app\n'
        return text+launch
    if kind == 'dotnet':
        runtime = selected.get('runtime_version') or '.'.join(selected['version'].split('.')[:2])
        text = '# Generated by StackPilot Linux recipes from version evidence\nFROM '+image+' AS builder\n'+PYTHON_SETUP+common
        text += 'RUN python3 .stackpilot-runtime/compiled_build.py dotnet && python3 .stackpilot-runtime/repository_tests.py && python3 .stackpilot-runtime/select_entrypoint.py dotnet /app /app/out/.stackpilot-entry.json\n'
        text += 'FROM mcr.microsoft.com/dotnet/aspnet:'+runtime+'\n'+PYTHON_SETUP+'WORKDIR /app\n'
        text += 'COPY --from=builder /app/out /app/out\nCOPY --from=builder /app/.stackpilot-tests.json /stackpilot-evidence/tests.json\n'
        text += 'COPY --from=builder /app/out/.stackpilot-entry.json /app/.stackpilot-entry.json\n'
        text += 'COPY .stackpilot-runtime /app/.stackpilot-runtime\nCOPY .stackpilot-plan.json /app/\n'
        text += 'RUN chown -R 65534:65534 /app\n'
        return text+f'ENV ASPNETCORE_URLS=http://+:{port}\n'+launch
    if kind == 'java':
        # Wrappers are the repository's build-tool authority; never substitute
        # a newer global Gradle/Maven for an omitted pinned toolchain.
        if not any((Path(root)/name).is_file() for name in ('mvnw', 'gradlew')): return None
        text = '# Generated by StackPilot Linux recipes from version evidence\nFROM '+image+'\n'+PYTHON_SETUP+common
        text += 'RUN python3 .stackpilot-runtime/linux_build.py java && chown -R 65534:65534 /app\n'
        return text+launch
    return None
