"""Typed deployment contracts and real native build templates.

stackpilot.json is optional. It resolves ambiguities rather than pretending a
repository filename specifies its entrypoint, OS, test requirements or release.
"""
import argparse
from concurrent.futures import ThreadPoolExecutor
import json
import os
from pathlib import Path
import re
import shutil
import sys

try:
    from repository_discovery import analyze
except ModuleNotFoundError:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]/'ai-service'/'app'))
    from repository_discovery import analyze

ASSETS = Path(__file__).resolve().parent
SKIP = {'.git','node_modules','.next','build','target','dist','.venv','venv','.stackpilot-runtime'}


def discover(root):
    result = []
    for current, dirs, files in os.walk(root, followlinks=False):
        dirs[:] = [d for d in dirs if d not in SKIP and not (Path(current)/d).is_symlink()]
        if len(Path(current).relative_to(root).parts)>5:
            dirs[:] = []
            continue
        if any(f in files for f in ('package.json','pyproject.toml','requirements.txt','setup.py','setup.cfg','Cargo.toml','go.mod','pom.xml','build.gradle','build.gradle.kts','Dockerfile','Gemfile','composer.json')) or any(name.endswith('.csproj') for name in files):
            result.append(str(Path(current).relative_to(root)))
        if len(result)>128:
            raise ValueError('Too many components; select deployment roots explicitly')
    return result


def plan(root, archetype):
    root = Path(root).resolve()
    config = json.loads((root/'stackpilot.json').read_text()) if (root/'stackpilot.json').is_file() else {}
    from repository_plan import normalize
    config, graph = normalize(root,config)
    if not isinstance(config,dict) or config.get('version',1) != 1:
        raise ValueError('Unsupported stackpilot.json contract version')
    if config.get('process_checks') and graph is None:
        raise ValueError('process_checks require a version 2 component contract for broker worker execution')
    build_recipe = config.get('build_recipe')
    if build_recipe is not None and not isinstance(build_recipe,dict):
        raise ValueError('build_recipe must be an object')
    build_recipe = build_recipe or {}
    discovery = analyze(root)
    entrypoint = config.get('entrypoint') or discovery['entrypoint']
    # A submitted Dockerfile is an explicit delivery recipe. Do not override it
    # from unrelated utility scripts; generated launch.py recipes can adapt.
    docker_path = root/'Dockerfile'
    generated = docker_path.is_file() and any(marker in docker_path.read_text() for marker in ('.stackpilot-runtime/launch.py', '# Generated by StackPilot Linux recipes'))
    inferred = discovery['workload'] if discovery['workload'] == 'cli' and (not docker_path.exists() or generated) else 'web'
    workload = config.get('workload', inferred)
    if workload not in {'web','api','cli','worker','job','tcp','grpc','artifact','desktop','android','ios','macos','windows','package'}:
        raise ValueError('Unknown workload contract')
    native = {'native_android':'android', 'desktop_compose_gui':'desktop', 'windows_desktop_exe':'windows', 'native_ios':'ios'}
    if 'workload' not in config and archetype in native:
        workload = native[archetype]
    protocol = 'process' if workload == 'worker' else 'tcp' if workload in {'tcp','grpc'} else 'http'
    health = config.get('health',{})
    if not isinstance(health,dict):raise ValueError('health must be an object')
    path = health.get('path','/healthz' if workload in {'android','artifact','package','cli','job'} else '/')
    if not isinstance(path,str) or not path.startswith('/') or path.startswith('//') or '\\' in path or any(c in path for c in '\r\n'):
        raise ValueError('Health path must be an absolute HTTP path')
    port = config.get('port',0)
    if isinstance(port,bool) or not isinstance(port,int) or port<0 or port>65535:
        raise ValueError('Invalid application port')
    if not port and (root/'Dockerfile').is_file():
        # Base images can expose other ports (nginx:80). The submitted final
        # stage's explicit port is stronger evidence than image map ordering.
        docker=(root/'Dockerfile').read_text(encoding='utf-8')
        final=re.split(r'^\s*FROM\s+',docker,flags=re.M|re.I)[-1]
        declarations=[]
        for value in re.findall(r'^\s*EXPOSE\s+([^\n]+)',final,flags=re.M|re.I):
            declarations.extend(int(token.split('/')[0]) for token in value.split() if re.fullmatch(r'\d+(?:/tcp)?',token))
        unique=set(declarations)
        if len(unique)==1:port=unique.pop()
    if workload in {'cli','job','package'}:port=3000
    checks = config.get('checks',[])
    if not isinstance(checks,list) or len(checks)>50:
        raise ValueError('Checks must be a bounded list')
    for check in checks:
        if not isinstance(check,dict) or not isinstance(check.get('path'),str) or not check['path'].startswith('/') or check['path'].startswith('//') or '\\' in check['path'] or any(c in check['path'] for c in '\r\n'):
            raise ValueError('Check paths must be relative to the deployment origin')
        if 'json_contains' in check and not isinstance(check['json_contains'],dict):raise ValueError('json_contains must be an object')
    for statuses in [health.get('statuses',[200]),*(c.get('statuses',[200]) for c in checks)]:
        if not isinstance(statuses,list) or not statuses or any(isinstance(s,bool) or not isinstance(s,int) or s<100 or s>599 for s in statuses):raise ValueError('Accepted statuses must be valid HTTP codes')
    if workload in {'cli','job'} and not (entrypoint or build_recipe.get('runtime_command')):
        raise ValueError('Console/jobs need an explicit entrypoint argument array or an unambiguous interactive Python program')
    if 'entrypoint' in config and (not isinstance(config['entrypoint'],list) or not config['entrypoint'] or any(not isinstance(a,str) or not a or '\0' in a for a in config['entrypoint'])):
        raise ValueError('entrypoint must be a nonempty executable argument array')
    if workload == 'package' and not config.get('build_recipe'):
        raise ValueError('Packages require a build_recipe with explicit tested package outputs')
    job_timeout = config.get('job_timeout_seconds',3600)
    if type(job_timeout) is not int or not 1 <= job_timeout <= 86400:
        raise ValueError('Finite job execution deadline must be an integer between 1 and 86400 seconds')
    console_scenarios = config.get('console_scenarios',[])
    if not isinstance(console_scenarios,list) or len(console_scenarios)>20:
        raise ValueError('Console scenarios must be a bounded list')
    total_console_steps = 0
    for scenario in console_scenarios:
        steps = scenario.get('steps') if isinstance(scenario,dict) else None
        if not isinstance(steps,list) or not steps or not isinstance(scenario.get('name'),str):
            raise ValueError('Console scenario needs a name and input/output steps')
        total_console_steps += len(steps)
        for step in steps:
            if not isinstance(step,dict) or not set(step) <= {'input','output_contains','exit_code'}:
                raise ValueError('Unsupported console step')
            if 'input' in step and (not isinstance(step['input'],str) or not 0 < len(step['input'].encode()) <= 4096):
                raise ValueError('Console input must be bounded text')
            if 'output_contains' in step and (not isinstance(step['output_contains'],str) or not 0 < len(step['output_contains']) <= 4096):
                raise ValueError('Console output assertion must be nonempty bounded text')
            if 'exit_code' in step and (type(step['exit_code']) is not int or not 0 <= step['exit_code'] <= 255):
                raise ValueError('Console exit assertion must be an exit status')
        if 'output_contains' not in steps[-1] and 'exit_code' not in steps[-1]:
            raise ValueError('Console scenario needs a final outcome assertion')
    if total_console_steps>100: raise ValueError('Too many console steps')
    tests = config.get('tests',[])
    build_secrets=config.get('build_secrets',[])
    if not isinstance(build_secrets,list) or len(build_secrets)>20 or any(not isinstance(key,str) or not re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]{0,127}',key) or key.startswith(('PUBLIC_','NEXT_PUBLIC_','VITE_','REACT_APP_')) for key in build_secrets) or len(set(build_secrets))!=len(build_secrets):raise ValueError('build_secrets must name bounded distinct private credential identifiers')
    if not isinstance(tests,list) or any(not isinstance(t,list) or not t or any(not isinstance(a,str) for a in t) for t in tests):
        raise ValueError('Test commands must be arrays of arguments, run in the isolated image')
    browser_checks=config.get('browser_checks',[])
    if not isinstance(browser_checks,list) or len(browser_checks)>50 or any(not isinstance(c,dict) for c in browser_checks):
        raise ValueError('browser_checks must be a bounded list of assertion objects')
    for assertion in browser_checks:
        if assertion.get('kind') not in {'text','value','visible','in_viewport','absent','checked','url','title'} or 'element_id' in assertion:
            raise ValueError('Release assertions require stable selectors or URL/title expectations')
        if assertion['kind'] not in {'url','title'} and (not isinstance(assertion.get('selector'),str) or not 0<len(assertion['selector'])<=500):
            raise ValueError('Release assertion requires a bounded stable selector')
    for flag in ('tests_required','fail_on_console_error','native_preview_required'):
        if flag in config and not isinstance(config[flag],bool):raise ValueError(flag+' must be boolean')
    if config.get('app_id') and (not isinstance(config['app_id'],str) or not re.fullmatch(r'[A-Za-z][A-Za-z0-9_]*(\.[A-Za-z][A-Za-z0-9_]*)+',config['app_id'])):raise ValueError('Invalid native app_id')
    native_scenarios=config.get('native_scenarios',[])
    if not isinstance(native_scenarios,list) or len(native_scenarios)>20:raise ValueError('Native scenarios must be a bounded list')
    total_native=0
    for scenario in native_scenarios:
        steps=scenario.get('steps') if isinstance(scenario,dict) else None
        if not isinstance(steps,list) or not steps or any(not isinstance(s,dict) for s in steps) or steps[-1].get('action')!='assert' or not steps[-1].get('expectations'):raise ValueError('Native scenarios need final outcome assertions')
        total_native+=len(steps)
    if total_native>100:raise ValueError('Too many native scenario actions')
    test_services=config.get('test_services',[])
    if not isinstance(test_services,list) or len(test_services)>128 or any(not isinstance(s,str) or not re.fullmatch(r'[a-zA-Z0-9_.-]+',s) for s in test_services):
        raise ValueError('test_services must name Compose services')
    scenarios=config.get('scenarios',[])
    monitor_scenarios=config.get('monitor_scenarios',[])
    if not isinstance(monitor_scenarios,list) or len(monitor_scenarios)>20:raise ValueError('Too many monitoring scenarios')
    if not isinstance(scenarios,list) or len(scenarios)>20:raise ValueError('Too many browser scenarios')
    total_steps=0
    for scenario in scenarios+monitor_scenarios:
        if not isinstance(scenario,dict) or not isinstance(scenario.get('name'),str) or not scenario['name']:raise ValueError('Scenario needs a name')
        route=scenario.get('path','/')
        if not isinstance(route,str) or not route.startswith('/') or route.startswith('//') or '\\' in route or any(c in route for c in '\r\n'):raise ValueError('Scenario route must remain on the deployment origin')
        steps=scenario.get('steps');total_steps+=len(steps) if isinstance(steps,list) else 0
        if not isinstance(steps,list) or not steps or not isinstance(steps[-1],dict) or steps[-1].get('action')!='assert':raise ValueError('Scenario requires a final outcome assertion')
        for step in steps:
            if not isinstance(step,dict) or step.get('action') not in {'click','fill','select','check','press_key','assert'}:raise ValueError('Unsupported scenario action')
            action=step['action']
            if action in {'click','fill','select','check'} and (not isinstance(step.get('selector'),str) or not 0<len(step['selector'])<=500):raise ValueError('Scenario action needs a stable selector')
            if action in {'fill','select'} and not isinstance(step.get('value'),str):raise ValueError('Scenario action needs a string value')
            if action=='check' and type(step.get('checked')) is not bool:raise ValueError('Scenario checkbox needs desired state')
            if action=='press_key' and not isinstance(step.get('key'),str):raise ValueError('Scenario key is missing')
            if action=='assert' and (not isinstance(step.get('expectations'),list) or not step['expectations']):raise ValueError('Scenario assertion must have expectations')
    if total_steps>100:raise ValueError('Too many scenario steps')
    from portable_build import recipe
    recipe(config,workload)
    from linux_recipes import choose
    toolchain = choose(root,discovery,config) if not docker_path.exists() and not build_recipe else None
    capabilities = config.get('capabilities', [])
    if not isinstance(capabilities, list): raise ValueError('capabilities must be a list of sandbox requirement identifiers')
    from sandbox_capabilities import select as select_sandbox
    # Explicit repository recipes are deployment authority. Command-worker
    # image admission is stricter; no control-plane credentials enter either.
    sandbox = select_sandbox(['linux', 'docker', *capabilities], purpose='deployment')
    sandbox['proposed_toolchain_image'] = toolchain['image'] if toolchain else build_recipe.get('image')
    return {'version':1,'repository_plan':graph,'workload':workload,'protocol':protocol,'port':port,'health_path':path,
            'verification_scope':'artifact_delivery' if workload in {'android','artifact','package'} else 'console_workflow' if workload=='cli' else 'job_completion' if workload=='job' else 'render_smoke' if workload=='web' else 'http_contract' if protocol=='http' else 'tcp_connect' if protocol=='tcp' else 'process',
            'entrypoint':entrypoint,'repository_discovery':discovery,'toolchain':toolchain,'sandbox':sandbox,
            'runtime_command':build_recipe.get('runtime_command'),
            'console_scenarios':console_scenarios,'job_timeout_seconds':job_timeout,
            'accepted_statuses':health.get('statuses',[200]),'checks':checks,'tests':tests,'tests_required':config.get('tests_required',False),
            'build_secrets':build_secrets,
            'browser_checks':browser_checks,'fail_on_console_error':config.get('fail_on_console_error',True),'test_services':test_services,
            'scenarios':scenarios,
            'monitor_scenarios':monitor_scenarios,
            'app_id':config.get('app_id'),'native_preview_required':config.get('native_preview_required',False),
            'native_scenarios':config.get('native_scenarios',[]),
            'components':discover(root),'primary_service':config.get('primary_service'),
            'requires_worker':'macos' if workload in {'ios','macos'} else 'windows' if workload=='windows' else None,
            'native_interactive_preview':'requires_emulator_worker' if workload=='android' else 'requires_native_worker' if workload in {'ios','windows','macos'} else None}


def android_dockerfile():
    return '''FROM eclipse-temurin:21-jdk AS builder
RUN apt-get update && apt-get install -y --no-install-recommends python3 curl unzip && rm -rf /var/lib/apt/lists/*
ENV ANDROID_HOME=/opt/android-sdk ANDROID_SDK_ROOT=/opt/android-sdk
ARG ANDROID_TOOLS_VERSION=15859902
ARG ANDROID_TOOLS_SHA256=4e4c464f145a7512b57d088ac6c278c03c9eea610886b35a5e0804e74eedf583
RUN curl --fail --retry 3 -o /tmp/tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_TOOLS_VERSION}_latest.zip && echo "$ANDROID_TOOLS_SHA256  /tmp/tools.zip" | sha256sum -c - && mkdir -p /opt/android-sdk/cmdline-tools && unzip -q /tmp/tools.zip -d /opt/android-sdk/cmdline-tools && mv /opt/android-sdk/cmdline-tools/cmdline-tools /opt/android-sdk/cmdline-tools/latest && rm /tmp/tools.zip
ENV PATH=/opt/android-sdk/cmdline-tools/latest/bin:/opt/android-sdk/platform-tools:$PATH
RUN yes | sdkmanager --licenses >/dev/null
RUN sdkmanager "platform-tools"
WORKDIR /source
COPY .stackpilot-runtime/sdk_prepare.py /prepare-sdk.py
COPY .stackpilot-sdk.json /sdk-plan.json
RUN python3 /prepare-sdk.py /sdk-plan.json
COPY . .
RUN --mount=type=cache,target=/root/.gradle python3 .stackpilot-runtime/native_build.py android
FROM python:3.12-slim
WORKDIR /preview
COPY --from=builder /artifacts /artifacts
COPY .stackpilot-runtime/artifact_server.py /preview/server.py
ENV PORT=3000 ARTIFACT_ROOT=/artifacts
USER 65534:65534
EXPOSE 3000
HEALTHCHECK CMD python -c "import urllib.request; urllib.request.urlopen('http://127.0.0.1:3000/healthz',timeout=3)"
CMD ["python", "/preview/server.py"]
'''


def python_console_dockerfile():
    return '''FROM python:3.12-slim
WORKDIR /app
COPY . .
RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; elif [ -f pyproject.toml ] || [ -f setup.py ]; then pip install --no-cache-dir .; fi
RUN python .stackpilot-runtime/repository_tests.py && python .stackpilot-runtime/select_entrypoint.py python /app /app/.stackpilot-entry.json
ENV PORT=3000
USER 65534:65534
EXPOSE 3000
CMD ["python", "/app/.stackpilot-runtime/launch.py"]
'''


def node_console_dockerfile():
    return '''FROM node:22-bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends python3 && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . .
RUN node .stackpilot-runtime/node_tasks.cjs install
RUN if node -e 'process.exit(JSON.parse(require("fs").readFileSync("package.json")).scripts?.build ? 0 : 1)'; then node .stackpilot-runtime/node_tasks.cjs build; fi
RUN python3 .stackpilot-runtime/repository_tests.py
ENV PORT=3000
USER 65534:65534
EXPOSE 3000
CMD ["python3", "/app/.stackpilot-runtime/console_server.py"]
'''


def desktop_dockerfile():
    return '''FROM eclipse-temurin:21-jdk AS builder
RUN apt-get update && apt-get install -y --no-install-recommends python3 && rm -rf /var/lib/apt/lists/*
WORKDIR /source
COPY . .
RUN python3 .stackpilot-runtime/native_build.py desktop
FROM eclipse-temurin:21-jre
RUN apt-get update && apt-get install -y --no-install-recommends python3 xvfb openbox x11vnc novnc websockify wmctrl x11-utils fonts-dejavu-core libgl1 libfontconfig1 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /artifacts/application.jar /app/application.jar
COPY --from=builder /artifacts/manifest.json /stackpilot-evidence/tests.json
COPY .stackpilot-runtime/desktop_entrypoint.py /app/entrypoint.py
ENV STACKPILOT_APP_COMMAND='["java","-jar","/app/application.jar"]' HOME=/tmp
USER 65534:65534
EXPOSE 3000
CMD ["python3", "/app/entrypoint.py"]
'''


def prepare(root, archetype):
    root = Path(root).resolve()
    from repository_plan import normalize, prepare_components
    original=json.loads((root/'stackpilot.json').read_text()) if (root/'stackpilot.json').is_file() else {}
    normalized, graph=normalize(root,original)
    if graph:
        record=root/'.stackpilot-repository-plan.json'
        if record.is_symlink():raise ValueError('Reserved repository plan cannot be a symlink')
        record.write_text(json.dumps(graph,indent=2))
        try:
            component_contracts=prepare_components(root,normalized,graph,prepare)
        finally:
            # Keep the authoritative graph and acceptance inputs across retries.
            # A single component at the root temporarily uses v1 for recursion.
            (root/'stackpilot.json').write_text(json.dumps(original,indent=2))
    contract = plan(root, archetype)
    if graph:
        contract['repository_plan']=graph
        contract['component_contracts']=component_contracts
        if not contract['port']:
            contract['port']=component_contracts[graph['primary_component']]['port']
    assets = root/'.stackpilot-runtime'
    if assets.is_symlink():
        raise ValueError('Reserved runtime asset directory must not be a symlink')
    assets.mkdir(exist_ok=True)
    sources = {source.name:source for source in ASSETS.iterdir()
               if source.is_file() and source.suffix in {'.py','.js','.cjs'}}
    sources['repository_discovery.py'] = Path(analyze.__code__.co_filename)
    from repository_toolchains import discover as discover_toolchains
    sources['repository_toolchains.py'] = Path(discover_toolchains.__code__.co_filename)
    def copy_asset(source):
        target = assets/source.name
        if target.is_symlink():
            raise ValueError('Reserved runtime asset must not be a symlink')
        shutil.copyfile(source,target)
    # Independent helper writes can have high latency on mounted workspaces.
    # Keep the full helper set and finish every bounded copy before admission.
    with ThreadPoolExecutor(max_workers=min(8,len(sources))) as copies:
        list(copies.map(copy_asset,sources.values()))
    dockerfile = root/'Dockerfile'
    if dockerfile.is_symlink():
        raise ValueError('Dockerfile must not be a symlink')
    if dockerfile.is_file():
        contents = dockerfile.read_text()
        legacy_helper = '.stackpilot-runtime/node_tasks.js'
        if legacy_helper in contents:
            # Repair workspaces can retain a Dockerfile generated by a prior
            # StackPilot release. The helper is now CommonJS .cjs so it also
            # runs inside repositories with "type": "module".
            dockerfile.write_text(contents.replace(legacy_helper,'.stackpilot-runtime/node_tasks.cjs'))
    if (root/'.stackpilot-plan.json').is_symlink():raise ValueError('Reserved plan must not be a symlink')
    (root/'.stackpilot-plan.json').write_text(json.dumps(contract,indent=2))
    if contract['sandbox']['status'] != 'ready':
        raise ValueError('Required sandbox is unavailable; provisioning request: '+json.dumps(contract['sandbox']['provisioning']))
    if contract['workload']=='android':
        from sdk_prepare import packages
        if (root/'.stackpilot-sdk.json').is_symlink():raise ValueError('Reserved SDK plan must not be a symlink')
        (root/'.stackpilot-sdk.json').write_text(json.dumps(packages(root)))
    if not (root/'Dockerfile').exists():
        from portable_build import dockerfile
        config=json.loads((root/'stackpilot.json').read_text()) if (root/'stackpilot.json').is_file() else {}
        template = dockerfile(config,contract['workload'])
        if template is None:
            template = android_dockerfile() if contract['workload']=='android' else desktop_dockerfile() if archetype=='desktop_compose_gui' else None
        if template is None:
            from linux_recipes import dockerfile as linux_dockerfile
            template = linux_dockerfile(root,contract['repository_discovery'],config,contract)
        if template is None and contract['workload'] in {'cli','job'} and contract.get('entrypoint') and contract['entrypoint'][0].split('/')[-1] in {'python','python3'}:
            template = python_console_dockerfile()
        if template is None and contract['workload'] in {'cli','job'} and contract.get('entrypoint') and contract['entrypoint'][0]=='node' and (root/'package.json').is_file():
            template = node_console_dockerfile()
        if template:
            (root/'Dockerfile').write_text(template)
    return contract


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('root',type=Path)
    parser.add_argument('--archetype',default='standard_web')
    args = parser.parse_args()
    print(json.dumps(prepare(args.root,args.archetype)))
